name: CI-english-linter

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "lint-english":
  lint-english:
    name: lint-english
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install writegood
      run: npm install -g write-good
    - name: run writegood
      # Recursively find all .md files and run the write-good linter on them
      run: find . -name '*.md' | xargs write-good
